// ---------------------------------------------------------------------------
// College catalog — the recommendation universe. [Luke / dashboard lane]
//
// The dashboard recommends from this pool: schools the student hasn't picked
// yet, ranked by fit + their risk appetite. Reuses the `College` type from
// data.ts (read-only). When this app goes live on Butterbase, this list is
// replaced by a `colleges` table query; the seam stays the same.
//
// Approximate public figures, mirroring the demo conventions in data.ts.
// Spans tiers (safety -> reach), sizes, settings, and regions so the
// recommender has range to work with — including strong-but-underrated picks.
// ---------------------------------------------------------------------------

import type { College } from "./data";

export const CATALOG: College[] = [
  // ---- Reaches: elite, high prestige -------------------------------------
  {
    id: "stanford",
    name: "Stanford University",
    short: "Stanford",
    location: "Stanford, CA",
    acceptanceRate: 0.04,
    medianGpa: 3.96,
    medianSat: 1520,
    size: 7600,
    setting: "suburban",
    breadth: 0.9,
    vibeIntense: 0.8,
    strengths: ["CS", "Entrepreneurship", "Engineering", "Film"],
  },
  {
    id: "brown",
    name: "Brown University",
    short: "Brown",
    location: "Providence, RI",
    acceptanceRate: 0.05,
    medianGpa: 3.94,
    medianSat: 1500,
    size: 7200,
    setting: "urban",
    breadth: 0.99,
    vibeIntense: 0.5,
    strengths: ["Open Curriculum", "Creative Writing", "CS", "Public Health"],
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    short: "NU",
    location: "Evanston, IL",
    acceptanceRate: 0.07,
    medianGpa: 3.92,
    medianSat: 1500,
    size: 8500,
    setting: "suburban",
    breadth: 0.85,
    vibeIntense: 0.7,
    strengths: ["Journalism", "Film", "Theatre", "Economics"],
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    short: "Vandy",
    location: "Nashville, TN",
    acceptanceRate: 0.07,
    medianGpa: 3.9,
    medianSat: 1510,
    size: 7100,
    setting: "urban",
    breadth: 0.82,
    vibeIntense: 0.65,
    strengths: ["Music", "Pre-Med", "Education", "Economics"],
  },
  {
    id: "pomona",
    name: "Pomona College",
    short: "Pomona",
    location: "Claremont, CA",
    acceptanceRate: 0.07,
    medianGpa: 3.93,
    medianSat: 1490,
    size: 1700,
    setting: "suburban",
    breadth: 0.96,
    vibeIntense: 0.45,
    strengths: ["Liberal Arts", "Economics", "CS", "Environmental Analysis"],
  },

  // ---- Targets: selective, strong, varied --------------------------------
  {
    id: "umich",
    name: "University of Michigan",
    short: "UMich",
    location: "Ann Arbor, MI",
    acceptanceRate: 0.18,
    medianGpa: 3.88,
    medianSat: 1450,
    size: 32000,
    setting: "suburban",
    breadth: 0.88,
    vibeIntense: 0.65,
    strengths: ["Engineering", "Business", "Public Policy", "Film"],
  },
  {
    id: "tufts",
    name: "Tufts University",
    short: "Tufts",
    location: "Medford, MA",
    acceptanceRate: 0.1,
    medianGpa: 3.9,
    medianSat: 1480,
    size: 6700,
    setting: "suburban",
    breadth: 0.9,
    vibeIntense: 0.55,
    strengths: ["International Relations", "Engineering", "Drama", "Biology"],
  },
  {
    id: "bu",
    name: "Boston University",
    short: "BU",
    location: "Boston, MA",
    acceptanceRate: 0.14,
    medianGpa: 3.8,
    medianSat: 1440,
    size: 18000,
    setting: "urban",
    breadth: 0.85,
    vibeIntense: 0.6,
    strengths: ["Communications", "Film", "Business", "Health Sciences"],
  },
  {
    id: "wisconsin",
    name: "University of Wisconsin–Madison",
    short: "UW",
    location: "Madison, WI",
    acceptanceRate: 0.49,
    medianGpa: 3.8,
    medianSat: 1380,
    size: 35000,
    setting: "urban",
    breadth: 0.85,
    vibeIntense: 0.5,
    strengths: ["Communications", "Biology", "Engineering", "Journalism"],
  },
  {
    id: "davidson",
    name: "Davidson College",
    short: "Davidson",
    location: "Davidson, NC",
    acceptanceRate: 0.17,
    medianGpa: 3.85,
    medianSat: 1420,
    size: 1900,
    setting: "suburban",
    breadth: 0.93,
    vibeIntense: 0.45,
    strengths: ["Liberal Arts", "Pre-Med", "Economics", "Writing"],
  },
  {
    id: "macalester",
    name: "Macalester College",
    short: "Mac",
    location: "Saint Paul, MN",
    acceptanceRate: 0.28,
    medianGpa: 3.8,
    medianSat: 1410,
    size: 2200,
    setting: "urban",
    breadth: 0.95,
    vibeIntense: 0.4,
    strengths: ["International Studies", "Economics", "Creative Writing", "Environmental Studies"],
  },
  {
    id: "occidental",
    name: "Occidental College",
    short: "Oxy",
    location: "Los Angeles, CA",
    acceptanceRate: 0.36,
    medianGpa: 3.7,
    medianSat: 1360,
    size: 2000,
    setting: "urban",
    breadth: 0.94,
    vibeIntense: 0.4,
    strengths: ["Film", "Liberal Arts", "Politics", "Creative Writing"],
  },
  {
    id: "kenyon",
    name: "Kenyon College",
    short: "Kenyon",
    location: "Gambier, OH",
    acceptanceRate: 0.34,
    medianGpa: 3.75,
    medianSat: 1390,
    size: 1800,
    setting: "rural",
    breadth: 0.95,
    vibeIntense: 0.35,
    strengths: ["Creative Writing", "English", "Drama", "Liberal Arts"],
  },
  {
    id: "fordham",
    name: "Fordham University",
    short: "Fordham",
    location: "New York, NY",
    acceptanceRate: 0.54,
    medianGpa: 3.7,
    medianSat: 1370,
    size: 9800,
    setting: "urban",
    breadth: 0.82,
    vibeIntense: 0.55,
    strengths: ["Business", "Communications", "Theatre", "Economics"],
  },

  // ---- Safeties: accessible, still strong --------------------------------
  {
    id: "syracuse",
    name: "Syracuse University",
    short: "Cuse",
    location: "Syracuse, NY",
    acceptanceRate: 0.52,
    medianGpa: 3.6,
    medianSat: 1310,
    size: 15000,
    setting: "urban",
    breadth: 0.83,
    vibeIntense: 0.5,
    strengths: ["Communications", "Architecture", "Film", "Sport Management"],
  },
  {
    id: "psu",
    name: "Penn State University",
    short: "PSU",
    location: "University Park, PA",
    acceptanceRate: 0.55,
    medianGpa: 3.6,
    medianSat: 1300,
    size: 40000,
    setting: "suburban",
    breadth: 0.86,
    vibeIntense: 0.5,
    strengths: ["Engineering", "Business", "Communications", "Meteorology"],
  },
  {
    id: "clark",
    name: "Clark University",
    short: "Clark",
    location: "Worcester, MA",
    acceptanceRate: 0.53,
    medianGpa: 3.55,
    medianSat: 1300,
    size: 2400,
    setting: "urban",
    breadth: 0.92,
    vibeIntense: 0.35,
    strengths: ["Psychology", "Environmental Science", "Film", "Liberal Arts"],
  },
  {
    id: "asu",
    name: "Arizona State University",
    short: "ASU",
    location: "Tempe, AZ",
    acceptanceRate: 0.9,
    medianGpa: 3.5,
    medianSat: 1240,
    size: 65000,
    setting: "urban",
    breadth: 0.9,
    vibeIntense: 0.45,
    strengths: ["Business", "Engineering", "Film", "Journalism"],
  },
  {
    id: "uvm",
    name: "University of Vermont",
    short: "UVM",
    location: "Burlington, VT",
    acceptanceRate: 0.62,
    medianGpa: 3.6,
    medianSat: 1290,
    size: 11000,
    setting: "suburban",
    breadth: 0.85,
    vibeIntense: 0.4,
    strengths: ["Environmental Studies", "Health Sciences", "Business", "Biology"],
  },
];

/**
 * The full universe the dashboard ranks over: the student's own colleges
 * (seeded + agent-sourced) plus the catalog, de-duped by id. The student's
 * own rows win on conflict (they may carry agent-verified fields).
 */
export function getUniverse(colleges: College[]): College[] {
  const byId = new Map<string, College>();
  CATALOG.forEach((c) => byId.set(c.id, c));
  colleges.forEach((c) => byId.set(c.id, c)); // student's rows override catalog
  return Array.from(byId.values());
}
